const add = require('./add.png');
const arrow_right = require('./arrow_right.png');
const clock_0 = require('./clock_0.png');
const clock_1 = require('./clock_1.png');
const clock_2 = require('./clock_2.png');
const clock_3 = require('./clock_3.png');
const clock_4 = require('./clock_4.png');
const clock_5 = require('./clock_5.png');
const clock_6 = require('./clock_6.png');
const clock_7 = require('./clock_7.png');
const close = require('./close.png');
const close_1 = require('./close_1.png');
const delete_icon = require('./delete_icon.png');
const done = require('./done.png');
const mode_0 = require('./mode_0.png');
const mode_1 = require('./mode_1.png');
const mode_2 = require('./mode_2.png');
const mode_3 = require('./mode_3.png');
const mode_4 = require('./mode_4.png');
const sort = require('./sort.png');

export default { add, arrow_right, clock_0, clock_1, clock_2, clock_3, clock_4, clock_5, clock_6, clock_7, close, close_1, delete_icon, done, mode_0, mode_1, mode_2, mode_3, mode_4, sort };