export default {
  networkTimingCode: 'network_timing',
  timeSyncCode: 'time_sync',
  wetherOnOffCode: 'wather_onofff',
  backLightCode: 'backlight_enum',
  playListCode: 'play_list',
  clock1SwitchCode: 'clock_1',
  clock2SwitchCode: 'clock_2',
  alarm1SettingCode: 'alarm1_setting',
  alarm2SettingCode: 'alarm2_setting',
  clockStatusCode: 'clock_status',
  alarmStopCode: 'alarm_stop',
  snoozeCode: 'snooze',
  brightValueCode: 'bright_value',
  sceneDataCode: 'scene_data',
  controlDataCode: 'control_data',
  countdownCode: 'countdown',
  openPlanCode: 'mic_music_data',
  brightnessControlCode: 'brightness_control',
  hsColorSet: 'hs_color_set',
  sleepAidStatusCode: 'sleep_aid_status',
  switchFaSleepCode: 'sleep',
  sleepSettingCode: 'sleep_setting',
  playListStateCode: 'play_list_state',
  playListUpCode: 'play_list_up',
  playListDownCode: 'play_list_down',
  playModeCode: 'play_mode',
};
